name: TransportPipes
version: ${project.version}
authors: [RoboTricker, BlackBeltPanda]
main: ${project.groupId}.transportpipes.${project.parent.name}
depend: [ProtocolLib]
softdepend: [LWC, AuthMe, WorldEdit]
api-version: 1.16
permissions:
  transportpipes.*:
    children:
      transportpipes.tps: true
      transportpipes.creative: true
      transportpipes.settings: true
      transportpipes.craft.*: true
  transportpipes.tps:
    default: op
  transportpipes.creative:
    default: op
  transportpipes.settings:
    default: true
  transportpipes.craft.*:
    default: true
    children:
      transportpipes.craft.coloredpipe: true
      transportpipes.craft.extractionpipe: true
      transportpipes.craft.craftingpipe: true
      transportpipes.craft.goldenpipe: true
      transportpipes.craft.icepipe: true
      transportpipes.craft.ironpipe: true
      transportpipes.craft.voidpipe: true
      transportpipes.craft.wrench: true
